LIBRARY ieee;
USE ieee.std_logic_1164.all;
ENTITY pulseGen IS PORT(
	CLR,CLK:	IN  STD_LOGIC;
	SEL0   :  OUT STD_LOGIC;
	T0,T1,T2,T3,T4,T5,T6,T7: OUT STD_LOGIC);
END pulseGen;

ARCHITECTURE bdf OF pulseGen IS

COMPONENT DFF74 PORT(
	PRn,CLRn,D,CLK: IN STD_LOGIC;
	Q,Qn: OUT STD_LOGIC);
END COMPONENT;

SIGNAL S0,S1,S2,S3,S4,S5,S6,S7:STD_LOGIC;
SIGNAL CLKn,SS1:STD_LOGIC;
SIGNAL CLK_1HZ:STD_LOGIC:='0';

BEGIN
PROCESS(CLK)
	variable CLK_COUNT:integer range 0 to 24999999;
	BEGIN
		IF(clk'EVENT AND clk='1')THEN
			IF(CLK_COUNT<24999999)THEN
				CLK_COUNT:=CLK_COUNT+1;
			ELSE
				CLK_COUNT:=0;
				CLK_1HZ<=NOT(CLK_1HZ);
			END IF;
		END IF;
	END PROCESS;
SS1 <= '1';
T0 <= S0;
T1 <= S1;
T2 <= S2;
T3 <= S3;
T4 <= S4;
T5 <= S5;
T6 <= S6;
T7 <= S7;
CLKn <= NOT(CLK_1HZ);
SEL0 <= NOT(SS1);
U0:DFF74 PORT MAP(PRn => CLR,CLRn => SS1,D => S7,CLK => CLKn,Q => S0);
U1:DFF74 PORT MAP(PRn => SS1,CLRn => CLR,D => S0,CLK => CLKn,Q => S1);
U2:DFF74 PORT MAP(PRn => SS1,CLRn => CLR,D => S1,CLK => CLKn,Q => S2);
U3:DFF74 PORT MAP(PRn => SS1,CLRn => CLR,D => S2,CLK => CLKn,Q => S3);
U4:DFF74 PORT MAP(PRn => SS1,CLRn => CLR,D => S3,CLK => CLKn,Q => S4);
U5:DFF74 PORT MAP(PRn => SS1,CLRn => CLR,D => S4,CLK => CLKn,Q => S5);
U6:DFF74 PORT MAP(PRn => SS1,CLRn => CLR,D => S5,CLK => CLKn,Q => S6);
U7:DFF74 PORT MAP(PRn => SS1,CLRn => CLR,D => S6,CLK => CLKn,Q => S7);
END bdf;